### ISSUE TITLE
Post in Nabble List

### ISSUE THREAD

**Issue by spapadias** [burgeraw/Gradoop-#11]
Make a nice post here http://apache-flink-user-mailing-list-archive.2336050.n4.nabble.com/
to ask developers for **proper** ways to distributedly **access** streaming graph state from downstream operators (other than those maintaining the state).

Essentially, how to **access** state that is stored in another node than the one doing the processing.

**Comment by burgeraw** [comment]
http://apache-flink-user-mailing-list-archive.2336050.n4.nabble.com/Distributed-Incremental-Streaming-Graph-Analytics-State-Accessing-Message-Passing-Options-td34496.html
